graph-walk:
  max_length : 64 # maximum length of the random walk
  min_length : 32 # maximum length of the random walk
  r: 0.25 # probability to jump to random layer
  depth: 100
  num_walks_per_node: 100

data:
  path : dbpedia-hdt
